/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ses;

import org.junit.Test;
//import static org.junit.Assert.*;

public class CheckNeighboursInGridTest {
    @Test public void appHasAGreeting() {
       // CheckNeighboursInGrid classUnderTest = new CheckNeighboursInGrid();
    }
}
